version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecomm-productservice-postgresql
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      TZ: Asia/Kolkata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: