version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecomm-orderservice-postgresql
    restart: always
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      TZ: Asia/Kolkata
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: